### ISSUE TITLE
linux version gamcrow 0.6.0 crashes during start

### ISSUE THREAD

**Issue by GrimmerSchnitter** [CmdrVasquess/gamcro#15]
Unfortunately, the linux version of gamcrow crashes during start.

System:
Debian Linux 10.8 on i5-8500 w/ 32GB 

Errorlog:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fc4b3ef3738]

runtime stack:
runtime.throw(0xa95f89, 0x2a)
	runtime/panic.go:1117 +0x72
runtime.sigpanic()
	runtime/signal_unix.go:718 +0x2e5

goroutine 66 [syscall, locked to thread]:
runtime.cgocall(0x96b1c0, 0xc000371670, 0x0)
	runtime/cgocall.go:154 +0x5b fp=0xc000371640 sp=0xc000371608 pc=0x430f9b
github.com/go-gl/gl/v3.2-core/gl._Cfunc_glowDrawArrays(0x7fc4b5f79780, 0x5, 0x4)
	_cgo_gotypes.go:6454 +0x45 fp=0xc000371670 sp=0xc000371640 pc=0x802ba5
github.com/go-gl/gl/v3.2-core/gl.DrawArrays(...)
	github.com/go-gl/gl@v0.0.0-20210501111010-69f74958bac0/v3.2-core/gl/package.go:9557
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).glDrawTexture(0xc000034ea0, 0x3f80000000000001)
	fyne.io/fyne/v2@v2.0.3/internal/painter/gl/gl_core.go:248 +0xed fp=0xc000371698 sp=0xc000371670 pc=0x82656d
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).drawTextureWithDetails(0xc000034ea0, 0xc016d8, 0xc000168b60, 0xc000371750, 0x4234000041400000, 0x41a8000042f80000, 0x43eb0000438a8000, 0x0, 0x3f800000)
	fyne.io/fyne/v2@v2.0.3/internal/painter/gl/draw.go:29 +0x15f fp=0xc0003716f8 sp=0xc000371698 pc=0x822b9f
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).drawText(0xc000034ea0, 0xc000168b60, 0x4234000041400000, 0x43eb0000438a8000)
	fyne.io/fyne/v2@v2.0.3/internal/painter/gl/draw.go:78 +0x20a fp=0xc000371770 sp=0xc0003716f8 pc=0x8235aa
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).drawObject(0xc000034ea0, 0xc016d8, 0xc000168b60, 0x4234000041400000, 0x43eb0000438a8000)
	fyne.io/fyne/v2@v2.0.3/internal/painter/gl/draw.go:97 +0x3da fp=0xc0003717c0 sp=0xc000371770 pc=0x823a7a
fyne.io/fyne/v2/internal/painter/gl.(*glPainter).Paint(0xc000034ea0, 0xc016d8, 0xc000168b60, 0x4234000041400000, 0x43eb0000438a8000)
	fyne.io/fyne/v2@v2.0.3/internal/painter/gl/painter.go:70 +0x98 fp=0xc0003717f8 sp=0xc0003717c0 pc=0x826a18
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint.func1(0xc00047e180, 0x4234000041400000)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:439 +0xe3 fp=0xc000371860 sp=0xc0003717f8 pc=0x86e663
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTree.func1(0xc016d8, 0xc000168b60, 0x4234000041400000, 0x0, 0x4f0000004f000000, 0x439100)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:535 +0x142 fp=0xc0003718b0 sp=0xc000371860 pc=0x86ea42
fyne.io/fyne/v2/internal/driver.walkObjectTree(0xc016d8, 0xc000168b60, 0x4214000040800000, 0xc01e58, 0xc000312870, 0x4214000040800000, 0x0, 0x4f0000004f000000, 0xc000371d28, 0xc000371d00, ...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:169 +0x482 fp=0xc000371968 sp=0xc0003718b0 pc=0x728f02
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0xc01e58, 0xc000312870, 0x4214000040800000, 0xc013d8, 0xc0005fc980, 0x4214000040800000, 0x0, 0x4f0000004f000000, 0xc000371d28, 0xc000371d00, ...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:190 +0x3ff fp=0xc000371a20 sp=0xc000371968 pc=0x728e7f
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0xc013d8, 0xc0005fc980, 0x4080000040800000, 0xc01738, 0xc0002ba380, 0x4080000040800000, 0x0, 0x4f0000004f000000, 0xc000371d28, 0xc000371d00, ...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:190 +0x3ff fp=0xc000371ad8 sp=0xc000371a20 pc=0x728e7f
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0xc01738, 0xc0002ba380, 0x4080000040800000, 0xc013d8, 0xc00011a080, 0x4080000040800000, 0x0, 0x4f0000004f000000, 0xc000371d28, 0xc000371d00, ...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:190 +0x3ff fp=0xc000371b90 sp=0xc000371ad8 pc=0x728e7f
fyne.io/fyne/v2/internal/driver.walkObjectTree.func1(...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:176
fyne.io/fyne/v2/internal/driver.walkObjectTree(0xc013d8, 0xc00011a080, 0x6e015300, 0x0, 0x0, 0x0, 0x0, 0x4f0000004f000000, 0xc000371d28, 0xc000371d00, ...)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:190 +0x3ff fp=0xc000371c48 sp=0xc000371b90 pc=0x728e7f
fyne.io/fyne/v2/internal/driver.WalkVisibleObjectTree(0xc013d8, 0xc00011a080, 0xc000371d28, 0xc000371d00, 0x494fe5)
	fyne.io/fyne/v2@v2.0.3/internal/driver/util.go:134 +0x94 fp=0xc000371cb8 sp=0xc000371c48 pc=0x728a54
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTree(0xc00027e000, 0xc0000201e0, 0xc000371e00, 0xc000371de8)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:556 +0x15c fp=0xc000371d70 sp=0xc000371cb8 pc=0x86263c
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).walkTrees(0xc00027e000, 0xc000371e00, 0xc000371de8)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:563 +0x4f fp=0xc000371db8 sp=0xc000371d70 pc=0x8626ef
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).paint(0xc00027e000, 0x43eb0000438a8000)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:453 +0x129 fp=0xc000371e30 sp=0xc000371db8 pc=0x861ee9
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow.func1()
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:163 +0x88 fp=0xc000371e80 sp=0xc000371e30 pc=0x86f008
fyne.io/fyne/v2/internal/driver/glfw.(*window).RunWithContext(0xc0000ec1c0, 0xc00005cea8)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1204 +0x4f fp=0xc000371e98 sp=0xc000371e80 pc=0x86d68f
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).repaintWindow(0xc00007c910, 0xc0000ec1c0)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:154 +0x65 fp=0xc000371ed0 sp=0xc000371e98 pc=0x864545
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread.func1(0xc00007c910, 0xc00010c000, 0xc000112000)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:210 +0x309 fp=0xc000371fc8 sp=0xc000371ed0 pc=0x86f409
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc000371fd0 sp=0xc000371fc8 pc=0x499841
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).startDrawThread
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:181 +0xbd

goroutine 1 [syscall, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwGetMonitorPos(0x1980e40, 0xc00047d8b8, 0xc00047d8bc)
	_cgo_gotypes.go:1092 +0x45
github.com/go-gl/glfw/v3.3/glfw.(*Monitor).GetPos.func1(0xc00047d8b0, 0xc00047d8b8, 0xc00047d8bc)
	github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/monitor.go:89 +0x6d
github.com/go-gl/glfw/v3.3/glfw.(*Monitor).GetPos(0xc00047d8b0, 0x1, 0x1)
	github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/monitor.go:89 +0x72
fyne.io/fyne/v2/internal/driver/glfw.(*window).getMonitorForWindow(0xc0000ec1c0, 0x7)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:324 +0x105
fyne.io/fyne/v2/internal/driver/glfw.(*window).detectScale(0xc0000ec1c0, 0x855047)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:350 +0x2f
fyne.io/fyne/v2/internal/driver/glfw.(*window).moved(0xc0000ec1c0, 0xc000312990, 0x7d8, 0xb4)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:526 +0x3c
github.com/go-gl/glfw/v3.3/glfw.goWindowPosCB(0x1981510, 0xb4000007d8)
	github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:207 +0x62
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1574 +0x3c
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
	github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20210410170116-ea3d685f79fb/window.go:949 +0x25
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).tryPollEvents(0xc00007c910)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:224 +0x45
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).runGL(0xc00007c910)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/loop.go:102 +0x1fc
fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).Run(0xc00007c910)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/driver.go:80 +0x3a
fyne.io/fyne/v2/internal/driver/glfw.(*window).ShowAndRun(0xc0000ec1c0)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:450 +0x3d
main.main()
	github.com/CmdrVasquess/gamcro/gamcrow/main.go:119 +0x502

goroutine 6 [sleep]:
time.Sleep(0x22ecb25c00)
	runtime/time.go:193 +0xd2
fyne.io/fyne/v2/internal/painter.svgCacheJanitor.func1()
	fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:57 +0x109
sync.(*Once).doSlow(0x126b4d0, 0xc000024d90)
	sync/once.go:68 +0xec
sync.(*Once).Do(0x126b4d0, 0xc000024d90)
	sync/once.go:59 +0x45
created by fyne.io/fyne/v2/internal/painter.svgCacheJanitor
	fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:55 +0x9b

goroutine 7 [select]:
fyne.io/fyne/v2/data/binding.makeInfiniteQueue.func1(0xc000026180, 0xc0000100c8)
	fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:36 +0x145
created by fyne.io/fyne/v2/data/binding.makeInfiniteQueue
	fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:21 +0xb1

goroutine 8 [chan receive]:
fyne.io/fyne/v2/data/binding.processItems()
	fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:54 +0x45
created by fyne.io/fyne/v2/data/binding.init.0
	fyne.io/fyne/v2@v2.0.3/data/binding/queue.go:15 +0x35

goroutine 9 [syscall]:
syscall.Syscall6(0xe8, 0x8, 0xc00048fc2c, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x2, 0xc00048fc08)
	syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0x8, 0xc00048fc2c, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0xc0005f80d0, 0xc00048fc48)
	golang.org/x/sys@v0.0.0-20210426230700-d19ff857e887/unix/zsyscall_linux_amd64.go:77 +0x72
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc00002ea20, 0xc00048fd00, 0x0, 0x1)
	github.com/fsnotify/fsnotify@v1.4.9/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00007c9b0)
	github.com/fsnotify/fsnotify@v1.4.9/inotify.go:192 +0x206
created by github.com/fsnotify/fsnotify.NewWatcher
	github.com/fsnotify/fsnotify@v1.4.9/inotify.go:59 +0x1ab

goroutine 10 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1(0xc00007c9b0, 0xc00002b680, 0x40, 0xc000065ee0, 0xc000065ef0)
	fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:42 +0x5a
created by fyne.io/fyne/v2/app.watchFile
	fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:41 +0xef

goroutine 12 [chan receive]:
fyne.io/fyne/v2/app.newAppWithDriver.func1(0xc0000264e0, 0xc000250230)
	fyne.io/fyne/v2@v2.0.3/app/app.go:120 +0x3d
created by fyne.io/fyne/v2/app.newAppWithDriver
	fyne.io/fyne/v2@v2.0.3/app/app.go:118 +0x1df

goroutine 13 [syscall]:
syscall.Syscall6(0xe8, 0xc, 0xc0004afc2c, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	syscall/asm_linux_amd64.s:43 +0x5
golang.org/x/sys/unix.EpollWait(0xc, 0xc0004afc2c, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	golang.org/x/sys@v0.0.0-20210426230700-d19ff857e887/unix/zsyscall_linux_amd64.go:77 +0x72
github.com/fsnotify/fsnotify.(*fdPoller).wait(0xc00002ea40, 0x0, 0x0, 0x0)
	github.com/fsnotify/fsnotify@v1.4.9/inotify_poller.go:86 +0x91
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc00007ca00)
	github.com/fsnotify/fsnotify@v1.4.9/inotify.go:192 +0x206
created by github.com/fsnotify/fsnotify.NewWatcher
	github.com/fsnotify/fsnotify@v1.4.9/inotify.go:59 +0x1ab

goroutine 14 [chan receive]:
fyne.io/fyne/v2/app.watchFile.func1(0xc00007ca00, 0xc00002c4b0, 0x26, 0xc000065f80, 0xc000065f90)
	fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:42 +0x5a
created by fyne.io/fyne/v2/app.watchFile
	fyne.io/fyne/v2@v2.0.3/app/settings_desktop.go:41 +0xef

goroutine 42 [chan receive]:
fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme.func1(0xc000026780)
	fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:109 +0x34
created by fyne.io/fyne/v2/internal/painter.SvgCacheMonitorTheme
	fyne.io/fyne/v2@v2.0.3/internal/painter/svg_cache.go:107 +0x9c

goroutine 67 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*window).runEventQueue(0xc0000ec1c0)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1264 +0xb0
created by fyne.io/fyne/v2/internal/driver/glfw.(*gLDriver).createWindow.func1
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/window.go:1289 +0x113

goroutine 68 [chan receive]:
fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).setupThemeListener.func1(0xc00010c060, 0xc00027e000)
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:495 +0x47
created by fyne.io/fyne/v2/internal/driver/glfw.(*glCanvas).setupThemeListener
	fyne.io/fyne/v2@v2.0.3/internal/driver/glfw/canvas.go:493 +0xa6
```

**Comment by CmdrVasquess** [comment]
1st time I really have to dig into such details (I like about Go that I didn't have such hassle; back in the days C/C++ taught me how much time you can spend on it)
As far as I got it:
- Having stacks of many goroutines and the start `runtime.stack` indicates that the crash does not originate from one specific goroutine. (right?)
- Gamcro depends on quite some non-Go dependencies (via cgo). I would start searching there. (good idea?)

@GrimmerSchnitter: Could you provide the output of `ldd gamcrow`, please. Perhaps I can find something there (I cannot reproduce the problem on any of my machines)

**Comment by GrimmerSchnitter** [comment]
As requested: here is the output of ```ldd gamcrow```

```	linux-vdso.so.1 (0x00007ffff79f4000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fe4ebfc2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe4ebda4000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fe4ebc63000)
	libXtst.so.6 => /usr/lib/x86_64-linux-gnu/libXtst.so.6 (0x00007fe4eba5d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe4eb8da000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fe4eb59b000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fe4eb38e000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fe4eb188000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007fe4eaf78000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fe4eaf6b000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fe4eaf66000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe4eaf61000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe4eaf55000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe4eaf34000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fe4eaf2f000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fe4eaf05000)
	libxcb-xkb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1 (0x00007fe4eaee7000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fe4eaea5000)
	libxkbcommon-x11.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0 (0x00007fe4eae98000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe4eacd7000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fe4eaac5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe4ec035000)
	libnvidia-tls.so.418.181.07 => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.418.181.07 (0x00007fe4ea8c1000)
	libnvidia-glcore.so.418.181.07 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.418.181.07 (0x00007fe4e8c4d000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fe4e8a41000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fe4e883b000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fe4e8637000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fe4e8431000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fe4e8417000)
```

**Comment by GrimmerSchnitter** [comment]
I'm sorry, it seemed to be a false alarm.
I just tried to run the program again, and it showed up immediately.
After configuring, everything worked fine!

Sorry for the mess.

**Comment by CmdrVasquess** [comment]
Thanks for the feedback and the help! – At least the software behaves flaky, i.e. I'd not call it "false alarm". But the root cause seem to be hard to nail down.
Current conclusion: The cause might be somewhere in the dependency of fyne to OS's underlying graphics system. If you encounter problems please consult: [fyne Prerequisites](https://developer.fyne.io/started/#prerequisites)

I encourage everybody who finds new facts about this flaky behavior to share knowledge here. Thanks
